extract app requirements

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -26,12 +26,16 @@ jobs:
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
+
       - name: Setup python
         uses: actions/setup-python@v4
+        with:
+          cache: 'pip' # cache following pip dependencies
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install pylint
+          pip install -r ./app/requirements.txt || { echo "Failed to install dependencies" ; exit 1; }
       - name: Run pylint
         run: |
           pylint $(git ls-files '*.py')
@@ -81,9 +85,8 @@ jobs:
 
       - name: Setup python
         uses: actions/setup-python@v4
-        # cache pip dependencies
-        with:
-          cache: 'pip'
+        with: 
+          cache: 'pip' # cache following pip dependencies
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
