add unit tests step

diff --git a/.github/workflows/github-actions-practice.yml b/.github/workflows/github-actions-practice.yml
--- a/.github/workflows/github-actions-practice.yml
+++ b/.github/workflows/github-actions-practice.yml
@@ -67,3 +67,24 @@ jobs:
           config: .markdownlint.yml
           files: '**/*.md'
           ignore: node_modules
+
+  Unit-tests:
+    needs: [Check-editorconfig, Pylint, Black, Markdown-lint]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
+
+      - name: Setup python
+      # will resolve python version from .python-version file
+        uses: actions/setup-python@v4
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt || { echo "Failed to install dependencies" ; exit 1; }
+   
+      - name: Run unit tests with pytest
+        working-directory: ./app
+        run: |
+          python -m unittest
